name: Beehive Bit Bunker Bundle

on:
  push:
    branches: [ "bbbb" ]
  pull_request:
    branches: [ "bbbb" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: windows-latest
            workflow-preset: release-windows

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true

    #- name: Install Prerequisites Linux
    #  if: ${{matrix.os == 'ubuntu-latest'}}
    #  shell: bash
    #  env:
    #    DEBIAN_FRONTEND: noninteractive
    #  run: |
    #    ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
    #    echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
    #    sudo dpkg-reconfigure man-db

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
      with:
        cmake-version: '3.31'

    - name: Run Workflow
      run: |
        cmake --version
        cmake --workflow --preset ${{matrix.workflow-preset}}

    - name: Upload zip package artifacts
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        archive: false
        path: ${{github.workspace}}/build-simh-release/*.zip
        compression-level: 0
